language: python

python:
  - 3.5
  - 3.6

notifications:
  email:
    recipients:
      - nigelchiang@outlook.com
    on_success: change
    on_failure: always

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a69c3fc977374d4773ff
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

before_install:
  - sudo apt-get update
  - sudo apt-get -y install python-pip
  - sudo pip install --upgrade pip
  - pip install --upgrade pip
  - pip install -r requirements-dev.txt
  - export TEST=true
script:
  - nosetests test.py