language: python

python:
  - 3.5
  - 3.6
  - nightly

notifications:
  email:
    recipients:
      - nigelchiang@outlook.com
    on_success: change
    on_failure: always

  slack: damn1t:B8uaJpZSMh7R7rOkr8q9snjw

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a69c3fc977374d4773ff
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always


script:
  - nosetests test.py